import {test} from 'node:test';import assert from 'node:assert/strict';import {parseRSS,parseFred,nextMeeting,validateDistribution,extractArticle,handleAPI,analyze,retainedFred} from '../server/api.js';
test('RSS excludes invalid links and future dated stories',()=>{const now=Date.parse('2026-09-19');const xml='<rss><item><title>Policy &amp; rates</title><link>https://example.com/a</link><description><![CDATA[<b>Actual</b> evidence]]></description><pubDate>Fri, 18 Sep 2026 12:00:00 GMT</pubDate></item><item><title>Future</title><link>https://example.com/b</link><pubDate>Sun, 20 Sep 2026 12:00:00 GMT</pubDate></item></rss>';const rows=parseRSS(xml,'fed',now);assert.equal(rows.length,1);assert.equal(rows[0].title,'Policy & rates');assert.equal(rows[0].excerpt,'Actual evidence');});
test('FRED skips missing trailing observations',()=>assert.deepEqual(parseFred('observation_date,DFF\n2026-01-02,3.5\n2026-01-03,.','DFF'),{date:'2026-01-02',value:3.5}));
test('calendar picks the next decision day rather than start day',()=>{const html='2026 FOMC Meetings<div class="fomc-meeting__month"><strong>September</strong></div><div class="fomc-meeting__date">15-16*</div><div class="fomc-meeting__month"><strong>October</strong></div><div class="fomc-meeting__date">27-28</div>';assert.equal(nextMeeting(html,Date.parse('2026-09-19')).date,'2026-10-28T18:00:00.000Z');});
test('distribution rejects missing, nonfinite and non-normalized probabilities',()=>{for(const p of [{cut:.4,hold:.5},{cut:-.1,hold:.6,hike:.5},{cut:.1,hold:.1,hike:.1},{cut:NaN,hold:.5,hike:.5}])assert.throws(()=>validateDistribution({probabilities:p}));assert.deepEqual(validateDistribution({probabilities:{cut:.2,hold:.7,hike:.1}}),{cut:.20000000000000004,hold:.7000000000000001,hike:.10000000000000002});});
test('Fed article extraction reaches substantive paragraphs beyond nested header divs',()=>{const text='The Committee decided to raise the target range for the federal funds rate by a quarter of a percentage point.';const html='<div id="article"><div><p>September 16, 2026</p></div><div><p>'+text+'</p></div><p>For media inquiries contact staff.</p>';assert.equal(extractArticle(html),text);});
test('missing key withholds AI estimates',async()=>assert.equal((await analyze({})).status,'not_configured'));
test('analysis endpoint rejects cross-origin and invalid method before upstream calls',async()=>{assert.equal((await handleAPI(new Request('https://folio.test/api/analyze'))).status,405);assert.equal((await handleAPI(new Request('https://folio.test/api/analyze',{method:'POST',headers:{origin:'https://other.test'}}))).status,403);});

import snapshot from '../server/fred-snapshot.json' with {type:'json'};
test('retained FRED values carry provenance and expire after 72 hours',()=>{const t=Date.parse(snapshot.retrievedAt);assert.equal(retainedFred('DFF',t+1000).retrieval,'retained_snapshot');assert.equal(retainedFred('DFF',t+72*3600000),null);assert.equal(retainedFred('DFF',t-1),null);assert.equal(retainedFred('UNKNOWN',t+1000),null);});
