import {test} from 'node:test';import assert from 'node:assert/strict';
import {normalizePosts,chatterTasks} from '../server/chatter.js';
import {categorize,belongsToSignal} from '../public/signals.js';
import {selectEvidence} from '../server/signals.js';
test('community items reject future/stale dates and non-HTTPS URLs; mark unverified',()=>{const now=Date.now(),base={id:'1',title:'<b>Fed rate cut</b>',url:'https://example.com/post',publishedAt:new Date(now-10000).toISOString(),excerpt:'<p>Discussion</p>'};const out=normalizePosts([base,{...base,id:'2',url:'javascript:alert(1)'},{...base,id:'3',publishedAt:new Date(now+10000).toISOString()},{...base,id:'4',publishedAt:new Date(now-31*86400000).toISOString()}],'hn',now);assert.equal(out.length,1);assert.equal(out[0].kind,'community');assert.equal(out[0].title,'Fed rate cut');assert.match(out[0].coverage,/unverified/);});
test('topic triage can assign multiple signals without classifying unrelated chatter',()=>{assert.deepEqual(categorize({title:'Fed rate cuts as inflation cools'}),['fed','inflation']);assert.deepEqual(categorize({title:'A new programming language'}),[]);assert.equal(belongsToSignal({source:'hn',categories:['oil']},'oil'),true);assert.equal(belongsToSignal({source:'hn',categories:['oil']},'jobs'),false);});
test('social sources stay explicitly gated without access credentials',async()=>{const tasks=chatterTasks({}).filter(t=>t.configured===false);assert.equal(tasks.length,2);for(const task of tasks)await assert.rejects(task.run(),/credentials_required/);});
test('community volume cannot displace all primary evidence in model context',()=>{const now=new Date().toISOString();const make=(kind,i)=>({id:kind+i,kind,source:kind==='official'?'fed':'hn',categories:['fed'],publishedAt:now});const news=[...Array.from({length:50},(_,i)=>make('community',i)),...Array.from({length:10},(_,i)=>make('official',i)),...Array.from({length:10},(_,i)=>make('publisher',i))];const selected=selectEvidence({news},'fed');assert.equal(selected.filter(n=>n.kind==='official').length,6);assert.equal(selected.filter(n=>n.kind==='community').length,4);assert.equal(selected.filter(n=>n.kind==='publisher').length,4);});
test('multiple comments in one thread do not count as independent model evidence',()=>{const news=Array.from({length:8},(_,i)=>({id:'comment'+i,threadId:'one-thread',kind:'community',source:'hn',categories:['fed'],publishedAt:new Date().toISOString()}));assert.equal(selectEvidence({news},'fed').length,1);});
test('triage rejects non-economic inflation and recognizes Fed action headlines',()=>{assert.deepEqual(categorize({title:'Audit of token inflation in LLM services'}),[]);assert.ok(categorize({title:'Fed hikes rates as inflation worries grow'}).includes('fed'));});
import {parseRedditFeed} from '../server/reddit-feed.js';
test('Reddit Atom scraper uses publication date and safe comment links',()=>{const date=new Date(Date.now()-10000).toISOString();const entry=(url,d=date)=>`<entry><id>t3_test</id><title>Inflation &amp; rates</title><link href="${url}"/><published>${d}</published><content type="html">&lt;p&gt;Public discussion&lt;/p&gt;</content></entry>`;const posts=parseRedditFeed('<feed>'+entry('https://www.reddit.com/r/Economics/comments/test/')+entry('https://evil.example/')+entry('https://www.reddit.com/r/Economics/comments/future/',new Date(Date.now()+86400000).toISOString())+'</feed>');assert.equal(posts.length,1);assert.equal(posts[0].title,'Inflation & rates');assert.match(posts[0].excerpt,/Public discussion/);});
test('Reddit public-feed fallback is available without credentials',()=>{assert.equal(chatterTasks({}).filter(t=>t.name.startsWith('Reddit RSS')).length,3);assert.equal(chatterTasks({REDDIT_ACCESS_TOKEN:'test'}).filter(t=>t.name.startsWith('Reddit RSS')).length,0);});
test('X scraper dataset adapter normalizes results and keeps the token in a header',async()=>{const original=globalThis.fetch;let called;globalThis.fetch=async(url,options)=>{called={url,options};return Response.json([{id:'12345',text:'Inflation discussion',url:'https://x.com/i/web/status/12345',createdAt:new Date(Date.now()-10000).toISOString()}]);};try{const task=chatterTasks({APIFY_TOKEN:'test-private-token',APIFY_X_DATASET_ID:'dataset123'}).find(t=>t.name.startsWith('X '));assert.equal(task.configured,true);const posts=await task.run();assert.equal(posts.length,1);assert.equal(posts[0].source,'x');assert.match(posts[0].coverage,/Apify/);assert.equal(called.url.includes('test-private-token'),false);assert.equal(called.options.headers.Authorization,'Bearer test-private-token');}finally{globalThis.fetch=original;}});

test('Reddit saved fallback preserves IDs and rejects expired posts without starting a scraper',async()=>{const original=globalThis.fetch;const calls=[];globalThis.fetch=async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});return Response.json([{id:'reddit-t3_abc',title:'CPI discussion',url:'https://www.reddit.com/r/Economics/comments/abc/',publishedAt:new Date(Date.now()-86400000).toISOString()},{id:'reddit-t3_old',title:'Old post',url:'https://www.reddit.com/r/Economics/comments/old/',publishedAt:new Date(Date.now()-31*86400000).toISOString()}]);};try{const task=chatterTasks({FOLIO_STORE_URL:'https://store.example',FOLIO_STORE_KEY:'private'}).find(t=>t.name==='Reddit · saved collection');const posts=await task.run();assert.equal(posts.length,1);assert.equal(posts[0].id,'reddit-t3_abc');assert.equal(posts[0].retrieval,'stored');assert.deepEqual(calls.map(c=>c.body),[{action:'posts',source:'reddit'}]);}finally{globalThis.fetch=original;}});

test('community evidence includes available Reddit and X even when HN is busiest',()=>{const make=(source,id)=>({id,source,kind:'community',categories:['fed'],publishedAt:new Date().toISOString()});const d={news:[...Array.from({length:12},(_,i)=>make('hn','hn'+i)),make('reddit','reddit'),make('x','x')]};const chosen=selectEvidence(d,'fed');assert.equal(chosen.length,4);assert.ok(chosen.some(n=>n.source==='reddit'));assert.ok(chosen.some(n=>n.source==='x'));});
