import {test} from 'node:test';import assert from 'node:assert/strict';
import {forecastEvent,withBaseline} from '../server/forecasts.js';
function data(){const history=Array.from({length:120},(_,i)=>({date:new Date(Date.UTC(2016,9+i,1)).toISOString().slice(0,10),value:4+(i%2)*.1}));return {fetchedAt:'2026-09-19T00:00:00Z',events:{jobs:{value:history.at(-1).value}},macro:[{id:'UNRATE',date:history.at(-1).date,history,url:'https://fred.stlouisfed.org/series/UNRATE'}]};}
const now=Date.parse('2026-09-19T00:00:00Z');
test('forecast is normalized, conditioned and evaluated sequentially against a reference',()=>{const p=forecastEvent(data(),'jobs',now);assert.equal(p.status,'ready');assert.ok(Math.abs(Object.values(p.probabilities).reduce((a,b)=>a+b)-1)<1e-10);assert.ok(p.probabilities.lower>p.probabilities.higher);assert.equal(p.holdout.windows,24);assert.ok(p.holdout.brier<p.holdout.referenceBrier);assert.match(p.method,/not real-time validation/);});
test('monthly forecast refuses stale, short and mismatched baseline data',()=>{for(const variant of ['short','mismatch']){const d=data();if(variant==='short')d.macro[0].history=d.macro[0].history.slice(-20);if(variant==='gap')d.macro[0].history.splice(40,1);if(variant==='mismatch')d.events.jobs.value=8;assert.equal(forecastEvent(d,'jobs',now),null);}assert.equal(forecastEvent(data(),'jobs',now+100*86400000),null);assert.equal(forecastEvent(data(),'fed',now),null);});
test('future observations cannot affect monthly probabilities',()=>{const d=data(),before=forecastEvent(d,'jobs',now);d.macro[0].history.push({date:'2027-01-01',value:99});assert.deepEqual(forecastEvent(d,'jobs',now),before);});
test('CPI forecasts classify changes in rounded monthly inflation, not index levels',()=>{const d=data();d.macro[0].id='CPIAUCSL';let value=200;d.macro[0].history=d.macro[0].history.map((r,i)=>({date:r.date,value:value*=1+[.001,.003][i%2]}));d.events={inflation:{value:.3}};const p=forecastEvent(d,'inflation',now);assert.equal(p.status,'ready');assert.ok(p.probabilities.cooler>p.probabilities.hotter);});
test('news abstention preserves routing without pretending to update the baseline',()=>{const base=forecastEvent(data(),'jobs',now),news={status:'insufficient_evidence',routes:[{id:'r',channel:'growth'}],evidenceAdequacy:.2};const merged=withBaseline(news,base);assert.deepEqual(merged.probabilities,base.probabilities);assert.deepEqual(merged.routes,news.routes);assert.equal(merged.newsAssessment.status,'insufficient_evidence');const ready={status:'ready',probabilities:{lower:.2,same:.4,higher:.4}};assert.equal(withBaseline(ready,base),ready);});

test('a missing month excludes its transition without bridging across the gap',()=>{const d=data(),full=forecastEvent(d,'jobs',now);d.macro[0].history.splice(40,1);const missing=forecastEvent(d,'jobs',now);assert.equal(missing.sampleSize,full.sampleSize-2);assert.ok(Object.values(missing.probabilities).every(Number.isFinite));});
