import test from 'node:test';import assert from 'node:assert/strict';
import {people,matchPeople,personExposure,peopleXQuery} from '../public/people.js';
test('current roles have dated primary-source provenance and distinct policy authority',()=>{assert.equal(people.length,10);assert.equal(people.find(p=>p.id==='warsh').role,'Federal Reserve chair');assert.equal(people.find(p=>p.id==='powell').role,'Federal Reserve governor');assert.ok(people.every(p=>p.source.startsWith('https://')&&p.reviewAfter));});
test('a name mention is never represented as a direct opinion',()=>{assert.equal(matchPeople({source:'x',title:'Scott Bessent said something',url:'https://x.com/random/status/1'})[0].relation,'reported_mention');});
test('a surname alone does not match a random person, but an official speech header does',()=>{assert.deepEqual(matchPeople({title:'Cook reveals new recipe',source:'reddit',url:'https://www.reddit.com/r/food'}),[]);assert.equal(matchPeople({title:'Bowman, Monetary policy',source:'speeches',url:'https://www.federalreserve.gov/newsevents/speech/a.htm'})[0].relation,'official_statement');assert.equal(matchPeople({title:'Bowman, Monetary policy',source:'speeches',url:'https://evil.example/speech'}).length,0);});
test('matched account authorship and institutional attribution stay distinct; retweets are not own opinions',()=>{const n={source:'x',title:'New outlook',url:'https://x.com/OPECSecretariat/status/1',authorHandle:'OPECSecretariat'};assert.equal(matchPeople(n)[0].relation,'institutional_post');assert.equal(matchPeople({...n,authorHandle:'SecScottBessent'})[0].relation,'own_post');assert.deepEqual(matchPeople({...n,isRetweet:true}),[]);});
test('portfolio exposure counts only mapped holdings and does not include cash',()=>{assert.equal(personExposure(people.find(p=>p.id==='warsh'),[40,20,15,10,10,5]),85);assert.ok(peopleXQuery.includes('from:SecScottBessent'));});

test('actionable statements prioritize direct relevant evidence and exclude unrelated celebrity mentions',async()=>{const {actionableStatements}=await import('../public/people.js');const a={id:'a',title:'Federal Reserve inflation guidance',categories:['fed'],people:[{personId:'warsh',relation:'reported_mention'}],publishedAt:'2026-09-19'};const b={...a,id:'b',people:[{personId:'waller',relation:'official_statement'}],publishedAt:'2026-09-18'};const c={...a,id:'c',title:'Movie premiere',categories:[]};assert.deepEqual(actionableStatements([a,c,b],'fed').map(n=>n.id),['b','a']);});
