import {store,storeConfigured} from './store.js';
import {parseRedditFeed} from './reddit-feed.js';
import {categorize} from '../public/signals.js';
const userAgent='FolioMacroResearch/1.0';
async function json(url,token){const r=await fetch(url,{headers:{'User-Agent':userAgent,...(token?{Authorization:`Bearer ${token}`}:{})},signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error(`Source returned ${r.status}`);return r.json();}
const strip=s=>String(s||'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#x27;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
export function normalizePosts(items,source,now=Date.now()){
 return items.filter(n=>n.id&&n.title&&/^https:\/\//.test(n.url)&&Number.isFinite(Date.parse(n.publishedAt))&&Date.parse(n.publishedAt)<=now&&now-Date.parse(n.publishedAt)<30*86400000).map(n=>({...n,id:source+'-'+String(source==='reddit'&&!/^t[13]_/.test(String(n.id))?'t3_'+n.id:n.id).replace(/[^a-zA-Z0-9_-]/g,''),source,publishedAt:new Date(n.publishedAt).toISOString(),sourceLabel:source==='hn'?'Hacker News':source==='reddit'?'Reddit':'X',kind:'community',title:strip(n.title).slice(0,240),excerpt:strip(n.excerpt).slice(0,1600),coverage:'Public discussion excerpt; unverified community content'}));
}
export function chatterTasks(env={}){
 return [
 ...(storeConfigured(env)?[{name:'Reddit · saved collection',kind:'news',url:'https://www.reddit.com/',run:()=>savedReddit(env)}]:[]),
 ...(!env.REDDIT_ACCESS_TOKEN?['Economics','investing','stocks'].map(sub=>({name:'Reddit RSS · r/'+sub,kind:'news',url:'https://www.reddit.com/r/'+sub+'/new/.rss',run:async()=>{const r=await fetch('https://www.reddit.com/r/'+sub+'/new/.rss',{headers:{'User-Agent':userAgent},signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error('Source returned '+r.status);return normalizePosts(parseRedditFeed(await r.text()),'reddit').map(n=>({...n,coverage:'Reddit public RSS title/excerpt; unverified community content',community:sub}));}})):[]),
 ...['inflation','federal reserve','unemployment','crude oil'].map(query=>({name:'Hacker News · '+query,kind:'news',url:'https://news.ycombinator.com/',run:async()=>{const j=await json('https://hn.algolia.com/api/v1/search_by_date?query='+encodeURIComponent(query)+'&tags=story&hitsPerPage=12&typoTolerance=false&numericFilters=created_at_i>'+Math.floor((Date.now()-30*86400000)/1000));const stories=normalizePosts((j.hits||[]).map(h=>({id:h.objectID,threadId:h.objectID,title:h.title,url:'https://news.ycombinator.com/item?id='+h.objectID,publishedAt:h.created_at,excerpt:h.story_text||h.title,engagement:h.points??null})), 'hn').filter(n=>categorize(n).length);const discussions=await Promise.allSettled(stories.slice(0,2).map(async story=>{const id=String(story.threadId);if(!/^\d+$/.test(id))return [];const thread=await json('https://hn.algolia.com/api/v1/items/'+id);return normalizePosts((thread.children||[]).slice(0,2).map(c=>({id:c.id,threadId:id,title:story.title,url:'https://news.ycombinator.com/item?id='+c.id,publishedAt:c.created_at,excerpt:c.text})), 'hn');}));return [...stories,...discussions.flatMap(r=>r.status==='fulfilled'?r.value:[])];}})),
 {name:'Reddit OAuth · optional extended access',kind:'news',url:'https://www.reddit.com/r/Economics/',configured:!!env.REDDIT_ACCESS_TOKEN,run:async()=>{if(!env.REDDIT_ACCESS_TOKEN)throw new Error('credentials_required');const j=await json('https://oauth.reddit.com/r/Economics+investing+stocks/new?limit=40&raw_json=1',env.REDDIT_ACCESS_TOKEN);return normalizePosts((j.data?.children||[]).map(({data:d})=>({id:d.id,title:d.title,url:'https://www.reddit.com'+d.permalink,publishedAt:new Date(d.created_utc*1000).toISOString(),excerpt:d.selftext||d.title,community:d.subreddit,engagement:d.score})), 'reddit');}},
 {name:'X · macro search',kind:'news',url:'https://x.com/',configured:storeConfigured(env)||!!env.X_BEARER_TOKEN||!!(env.APIFY_TOKEN&&env.APIFY_X_DATASET_ID),run:async()=>{if(storeConfigured(env))return normalizePosts((await store(env,'posts',{source:'x'})).map(n=>({...n,id:n.id.replace(/^x-/, '')})), 'x');if(!env.X_BEARER_TOKEN){if(!env.APIFY_TOKEN||!env.APIFY_X_DATASET_ID)throw new Error('credentials_required');if(!/^[a-zA-Z0-9]+$/.test(env.APIFY_X_DATASET_ID))throw new Error('Invalid dataset ID');const rows=await json('https://api.apify.com/v2/datasets/'+env.APIFY_X_DATASET_ID+'/items?clean=true&limit=50',env.APIFY_TOKEN);if(!Array.isArray(rows))throw new Error('Invalid scraper result');return normalizePosts(rows.map(d=>({id:d.id,title:d.text,url:d.url||'https://x.com/i/web/status/'+d.id,publishedAt:d.createdAt,excerpt:d.text})), 'x').map(n=>({...n,coverage:'Apify scraped public X post; unverified community content'}));}const query='(inflation OR "federal reserve" OR unemployment OR "crude oil") lang:en -is:retweet';const j=await json('https://api.x.com/2/tweets/search/recent?query='+encodeURIComponent(query)+'&max_results=30&tweet.fields=created_at',env.X_BEARER_TOKEN);return normalizePosts((j.data||[]).map(d=>({id:d.id,title:d.text,url:'https://x.com/i/web/status/'+d.id,publishedAt:d.created_at,excerpt:d.text})), 'x');}}
 ];
}

export async function savedReddit(env){
 const rows=await store(env,'posts',{source:'reddit'});
 return normalizePosts(rows.map(n=>({...n,id:n.id.replace(/^reddit-/,'' )})),'reddit').map(n=>({...n,retrieval:'stored',coverage:(n.coverage||'Reddit discussion')+' · retained collection; original publication time preserved'}));
}
